name: Build and Push to Docker Hub

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Option A: Use Docker Buildx with --load (builds locally, like regular docker build)
      - name: Build Docker Image (Buildx with --load)
        run: |
          docker buildx build \
            --load \
            -t ${{ secrets.DOCKER_USERNAME }}/is147:${{ github.run_number }} .

      # Option B (alternative): Use Buildx with --push (build and push in one step)
      # Uncomment this step and comment the one above if you'd rather push during build
      # - name: Build and Push Docker Image (Buildx with --push)
      #   run: |
      #     docker buildx build \
      #       --push \
      #       -t ${{ secrets.DOCKER_USERNAME }}/is147:${{ github.run_number }} .

      # Only needed if you use --load above (Option A)
      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/is147:${{ github.run_number }}
